#!/usr/bin/env bash
echo "Do you want to uninstall catbots?"
read -p "Press ENTER to confirm."

rm -rf ./build
rm -rf ./cathook
rm -rf ./cathook-ipc-server
rm -rf ./cathook-ipc-web-panel
rm -rf ./just-disable-vac
rm -rf ./user_instances
sudo rm -rf /opt/cathook/ipc
sudo rm /opt/cathook/bin/libcathook-textmode.so

echo "Uninstalled."
